apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: crane-skopeo-sync-gen
  annotations:
    description: |
      Evaluate the resources from a `crane-export` and generate a source yaml
      to be used with `skopeo sync --src yaml`.

      The `oc-registry-info` ClusterTask can be used to retrieve the internal
      and public registry URLs.

      In the `skopeo` Workspace, the result will always be stored in
      "source.yaml".
spec:
  params:
    - name: internal-registry-url
      type: string
      description: |
        This is the internal registry url (ie. image-registry.openshift-image-registry.svc:5000).
    - name: public-registry-url
      type: string
      description: |
        This is the public registry url.
  steps:
    - name: crane-skopeo-sync-gen
      image: quay.io/konveyor/crane-runner:latest
      script: |
        set -e
        set -o pipefail
        set -x

        crane skopeo-sync-gen \
          --export-dir="$(workspaces.export.path)" \
          --internal-registry-url="$(params.internal-registry-url)" \
          --registry-url="$(params.public-registry-url)" | tee "$(workspaces.skopeo.path)/source.yaml"
  workspaces:
    - name: export
      description: |
        This is the folder where the results of crane export were stored.
      mountPath: /var/crane/export
    - name: skopeo
      description: |
        This is the folder where we will store the results of crane skopeo-sync-gen.
      mountPath: /var/crane/skopeo
