apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: crane-apply
  annotations:
    description: |
      Generate YAML by applying transformations to the exported resources.
spec:
  steps:
    - name: crane-apply
      image: quay.io/konveyor/crane-runner:latest
      script: |
        set -e
        set -o pipefail
        set -x

        crane apply \
          --export-dir=$(workspaces.export.path) \
          --transform-dir=$(workspaces.transform.path) \
          --output-dir=$(workspaces.apply.path)
        find $(workspaces.apply.path)
  workspaces:
    - name: export
      description: |
        This is the folder where the results of crane export were stored.
      mountPath: /var/crane/export
    - name: transform
      description: |
        This is the folder where we will store the results of crane transform.
      mountPath: /var/crane/transform
    - name: apply
      description: |
        This is the folder where we will store the results of crane apply.
      mountPath: /var/crane/apply
