apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: kubectl-apply-kustomize
  annotations:
    description: |
      Run kubectl apply -k against a kustomize directory.
spec:
  # These are all required parameters to the task when we write a Pipeline using
  # this task, we must ensure that these parameters are supplied.
  params:
    - name: dest-context
      type: string
      description: The context from the kubeconfig that represents the destination cluster.
  steps:
    - name: kubectl-apply
      image: quay.io/djzager/crane-runner:d86e86f
      script: |
        # TODO(djzager): come up with better way to use internal ip
        kubectl --context $(params.dest-context) config view --flatten --minify > kubeconfig
        yq eval --inplace --exit-status '.clusters[0].cluster.server |= "https://kubernetes.default.svc"' kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig

        kubectl apply -k $(workspaces.kustomize.path)/
      env:
        - name: KUBECONFIG
          value: $(workspaces.kubeconfig.path)/config
  # https://github.com/tektoncd/pipeline/blob/main/docs/workspaces.md#using-workspaces-in-tasks
  workspaces:
    - name: kustomize
      description: |
        This is the folder storing a kustomization file to be applied.
    - name: kubeconfig
      description: |
        The user's kubeconfig
