name: Needs Triage

on:
  workflow_dispatch:

jobs:
  needs-triage:
    runs-on: ubuntu-latest
    steps:
      - name: Needs Triage
        id: create
        uses: konveyor/github-actions/gh-issue-slack-digest@main
        with:
          slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
          messageHeaderPrefix: "Issues needing triage"
          hasLabels: "needs-triage"
          mentionUsers: "@mtrho-triage-team"
